import Head from "next/head";
import SearchPage from "../components/SearchPage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hybr1d Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchPage />
    </div>
  );
}
