import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Search from "./Search";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hybr1d Search</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Search />
      </main>
    </div>
  );
}
